on:
  watch:
    types: [ started ]

jobs:
  run-on-star:
    runs-on: ubuntu-latest
    steps:
    - name: Download Giphy
      run: |
        GITHUB_STARS=$(curl -s https://api.github.com/repos/$USER/$REPO | jq .stargazers_count)
        GIPHY_RESPONSE=$(curl -s "http://api.giphy.com/v1/gifs/search?q=${GITHUB_STARS}&api_key=${{secrets.GIPHY_API_KEY}}&limit=1")
        GIPHY_URL=$(echo $GIPHY_RESPONSE | jq .data[0].images.original.url | cut -d '?' -f1)
        wget -q -O /tmp/giphy.gif $GIPHY_URL
    - name: Upload Giphy to Dropbox
        curl -X POST "https://api-content.dropbox.com/2/files/upload" -H "Authorization: Bearer ${{secrets.DROPBOX_API_KEY}}" \
          -H "Content-Type: application/octet-stream" -H "Dropbox-API-Arg: {\"path\": \"/giphy.gif\", \"mode\": \"overwrite\"}" \
          --data-binary @/tmp/giphy.gif
